### PR TITLE
Upgrade: update eslint dependency to ^3.0.0 (refs #15)

### PR DESCRIPTION
**Pull request by nostalic**
* Update tests to match updated error messages
* Update browserified eslint for codemirror demo page

### CODE REVIEW

**Comment by nostalic** [comment]
Hi @angelozerr 
[eslint v3.x dropped support for node < 4](https://eslint.org/docs/user-guide/migrating-to-3.0.0#dropping-support-for-nodejs--4) and updated their [travis config](https://github.com/eslint/eslint/blob/v3.0.0/.travis.yml) accordingly - while tern 0.21 is still supporting [node_js 0.10](https://github.com/ternjs/tern/blob/0.21.0/.travis.yml).

Are you ok with updating the travis config to match the one from eslint 3.x for this plugin?

**Comment by angelozerr** [comment]
> Are you ok with updating the travis config to match the one from eslint 3.x for this plugin?

Yes sure.

**Comment by nostalic** [comment]
Done!
Any other changes / check before this can be merged?
Should I update the `defaultConfig` to match changes in https://eslint.org/docs/user-guide/migrating-to-3.0.0#changes-to-eslintrecommended as well?

**Comment by nostalic** [comment]
@angelozerr I updated the `defaultConfig` to match eslint:recommended - could you review the changes and see if the pull request can be merged?

I am planning on updating the plugin to eslint v4.5 next - do you see any additional steps for the update in addition to the one listed below?

- [ ] Update eslint dependency in `package.json`
- [ ] Validate tests and update travis config to match eslint's
- [ ] Update browserified eslint in `demos`
- [ ] Update recommended setting in `defaultConfig` and update tests as appropriate

**Comment by angelozerr** [comment]
Thanks @nostalic !

**Pull request merged**
